---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kos-app
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kos-app-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: kos-app
  interval: 30s
