---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kos-app
  namespace: flux-system
spec:
  interval: 5m0s
  path: ../../../apps/kos-app
  prune: true
  sourceRef:
    kind: GitRepository
    name: kos-app
  targetNamespace: kos-app
